### PR TITLE
Fix for level

### PR DESCRIPTION
**Pull request by maciejo228**

### CODE REVIEW

**Review by grzedzicki — APPROVED** [review]
lgtm

**Review by MrMeky — APPROVED** [review]
It seems fine after being provided needed changes

**Review by Drejzer — APPROVED** [review]
Looks Good

**Review by MrMeky — CHANGES_REQUESTED** [review]
Multiple bugs occured as a result

**Review by Drejzer — CHANGES_REQUESTED** [review]
Conflict merge leftovers

**Pull request closed without merging**
